-- Historique 2011 importe de Leaguepedia (https://lol.fandom.com, CC BY-SA 3.0) par
-- import/import_leaguepedia.py : NE PAS EDITER A LA MAIN, regenerer le fichier.
-- Structure des tournois (phases, poules, brackets relies) SANS les scores : les
-- resultats se saisissent dans l'appli, les playoffs avancent au fil des scores.

CREATE TEMP TABLE lp_team (lp_name TEXT PRIMARY KEY, team_id BIGINT NOT NULL);
CREATE TEMP TABLE lp_match (k TEXT PRIMARY KEY, match_id BIGINT NOT NULL);

-- Equipe actuelle (apres renommages) : existante de meme nom, ou de meme code si elle
-- existe encore aujourd'hui ; sinon creee (code rendu unique si deja pris).
CREATE FUNCTION pg_temp.lp_team(p_name TEXT, p_code TEXT, p_region TEXT, p_active BOOLEAN) RETURNS BIGINT AS $$
DECLARE v_id BIGINT; v_code TEXT := p_code; n INT := 1;
BEGIN
    SELECT id INTO v_id FROM team WHERE lower(name) = lower(p_name) ORDER BY id LIMIT 1;
    IF v_id IS NULL AND p_active THEN
        SELECT id INTO v_id FROM team WHERE code = p_code ORDER BY id LIMIT 1;
    END IF;
    IF v_id IS NOT NULL THEN RETURN v_id; END IF;
    WHILE EXISTS (SELECT 1 FROM team WHERE code = v_code) LOOP
        n := n + 1;
        v_code := left(p_code, 18) || n;
    END LOOP;
    INSERT INTO team (code, name, region) VALUES (v_code, p_name, p_region) RETURNING id INTO v_id;
    RETURN v_id;
END $$ LANGUAGE plpgsql;

INSERT INTO lp_team VALUES ('Counter Logic Gaming', pg_temp.lp_team('Counter Logic Gaming', 'CLG', 'North America', FALSE));
INSERT INTO lp_team VALUES ('Epik Gamer', pg_temp.lp_team('Epik Gamer', 'EPIK', 'North America', FALSE));
INSERT INTO lp_team VALUES ('Fnatic', pg_temp.lp_team('Fnatic', 'FNC', 'EMEA', TRUE));
INSERT INTO lp_team VALUES ('TSM', pg_temp.lp_team('TSM', 'TSM', 'North America', FALSE));
INSERT INTO lp_team VALUES ('Team Pacific', pg_temp.lp_team('Pacific eSports', 'PCFC', 'SEA', FALSE));
INSERT INTO lp_team VALUES ('Team gamed!de', pg_temp.lp_team('Team gamed!de', 'GDE', 'Europe', FALSE));
INSERT INTO lp_team VALUES ('Xan', pg_temp.lp_team('Xan', 'XAN', 'SEA', FALSE));
INSERT INTO lp_team VALUES ('against All authority', pg_temp.lp_team('against All authority', 'AAA', NULL, FALSE));

-- Historique des noms (ex: SK Telecom T1 K -> SK Telecom T1 -> T1).
INSERT INTO team_name_history (team_id, name, short_name, valid_from, valid_to) SELECT team_id, 'Counter Logic Gaming', 'CLG', NULL, '2012-05-20' FROM lp_team WHERE lp_name = 'Counter Logic Gaming' ON CONFLICT (team_id, name) DO NOTHING;
INSERT INTO team_name_history (team_id, name, short_name, valid_from, valid_to) SELECT team_id, 'CLG Prime', NULL, '2012-05-21', NULL FROM lp_team WHERE lp_name = 'Counter Logic Gaming' ON CONFLICT (team_id, name) DO NOTHING;
INSERT INTO team_name_history (team_id, name, short_name, valid_from, valid_to) SELECT team_id, 'HawkshotGG', 'EPIK', NULL, '2010-08-06' FROM lp_team WHERE lp_name = 'Epik Gamer' ON CONFLICT (team_id, name) DO NOTHING;
INSERT INTO team_name_history (team_id, name, short_name, valid_from, valid_to) SELECT team_id, 'Epik Gamer', 'EPIK', '2010-08-07', NULL FROM lp_team WHERE lp_name = 'Epik Gamer' ON CONFLICT (team_id, name) DO NOTHING;

-- Worlds Season 1
INSERT INTO competition (code, name, type, region, season, split, start_date, end_date, source_key) VALUES ('WORLDS', 'Worlds Season 1', 'INTERNATIONAL_EVENT', NULL, 2011, NULL, '2011-06-18', '2011-06-20', 'leaguepedia:Season 1 World Championship');
INSERT INTO competition_stage (competition_id, position, name, format, best_of, team_count, group_count) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), 1, 'Phase de groupes', 'OTHER', NULL, 8, 1);
INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 1), 'Group Stage', '2011-06-18', '10:30:00', 'BO1', (SELECT team_id FROM lp_team WHERE lp_name = 'against All authority'), (SELECT team_id FROM lp_team WHERE lp_name = 'Epik Gamer'), 'SCHEDULED', 'REGULAR_SEASON', NULL);
INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 1), 'Group Stage', '2011-06-18', '11:45:00', 'BO1', (SELECT team_id FROM lp_team WHERE lp_name = 'Fnatic'), (SELECT team_id FROM lp_team WHERE lp_name = 'Team Pacific'), 'SCHEDULED', 'REGULAR_SEASON', NULL);
INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 1), 'Group Stage', '2011-06-18', '13:00:00', 'BO1', (SELECT team_id FROM lp_team WHERE lp_name = 'against All authority'), (SELECT team_id FROM lp_team WHERE lp_name = 'Fnatic'), 'SCHEDULED', 'REGULAR_SEASON', NULL);
INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 1), 'Group Stage', '2011-06-18', '13:00:00', 'BO1', (SELECT team_id FROM lp_team WHERE lp_name = 'Epik Gamer'), (SELECT team_id FROM lp_team WHERE lp_name = 'Team Pacific'), 'SCHEDULED', 'REGULAR_SEASON', NULL);
INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 1), 'Group Stage', '2011-06-18', '14:15:00', 'BO1', (SELECT team_id FROM lp_team WHERE lp_name = 'against All authority'), (SELECT team_id FROM lp_team WHERE lp_name = 'Team Pacific'), 'SCHEDULED', 'REGULAR_SEASON', NULL);
INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 1), 'Group Stage', '2011-06-18', '14:15:00', 'BO1', (SELECT team_id FROM lp_team WHERE lp_name = 'Epik Gamer'), (SELECT team_id FROM lp_team WHERE lp_name = 'Fnatic'), 'SCHEDULED', 'REGULAR_SEASON', NULL);
INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 1), 'Group Stage', '2011-06-18', '16:30:00', 'BO1', (SELECT team_id FROM lp_team WHERE lp_name = 'TSM'), (SELECT team_id FROM lp_team WHERE lp_name = 'Xan'), 'SCHEDULED', 'REGULAR_SEASON', NULL);
INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 1), 'Group Stage', '2011-06-18', '16:30:00', 'BO1', (SELECT team_id FROM lp_team WHERE lp_name = 'Team gamed!de'), (SELECT team_id FROM lp_team WHERE lp_name = 'Counter Logic Gaming'), 'SCHEDULED', 'REGULAR_SEASON', NULL);
INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 1), 'Group Stage', '2011-06-18', '18:00:00', 'BO1', (SELECT team_id FROM lp_team WHERE lp_name = 'Team gamed!de'), (SELECT team_id FROM lp_team WHERE lp_name = 'Xan'), 'SCHEDULED', 'REGULAR_SEASON', NULL);
INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 1), 'Group Stage', '2011-06-18', '19:15:00', 'BO1', (SELECT team_id FROM lp_team WHERE lp_name = 'TSM'), (SELECT team_id FROM lp_team WHERE lp_name = 'Counter Logic Gaming'), 'SCHEDULED', 'REGULAR_SEASON', NULL);
INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 1), 'Group Stage', '2011-06-18', '20:30:00', 'BO1', (SELECT team_id FROM lp_team WHERE lp_name = 'Counter Logic Gaming'), (SELECT team_id FROM lp_team WHERE lp_name = 'Xan'), 'SCHEDULED', 'REGULAR_SEASON', NULL);
INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 1), 'Group Stage', '2011-06-18', '20:30:00', 'BO1', (SELECT team_id FROM lp_team WHERE lp_name = 'TSM'), (SELECT team_id FROM lp_team WHERE lp_name = 'Team gamed!de'), 'SCHEDULED', 'REGULAR_SEASON', NULL);
INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 1), 'R1', '2011-06-19', '11:30:00', 'BO3', (SELECT team_id FROM lp_team WHERE lp_name = 'against All authority'), (SELECT team_id FROM lp_team WHERE lp_name = 'Team gamed!de'), 'SCHEDULED', 'REGULAR_SEASON', NULL);
INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 1), 'R1', '2011-06-19', '12:45:00', 'BO3', (SELECT team_id FROM lp_team WHERE lp_name = 'Counter Logic Gaming'), (SELECT team_id FROM lp_team WHERE lp_name = 'Fnatic'), 'SCHEDULED', 'REGULAR_SEASON', NULL);
INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 1), '5th Place', '2011-06-19', '15:00:00', 'BO1', (SELECT team_id FROM lp_team WHERE lp_name = 'Team gamed!de'), (SELECT team_id FROM lp_team WHERE lp_name = 'Counter Logic Gaming'), 'SCHEDULED', 'REGULAR_SEASON', NULL);
INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 1), 'R2', '2011-06-19', '16:00:00', 'BO3', (SELECT team_id FROM lp_team WHERE lp_name = 'against All authority'), (SELECT team_id FROM lp_team WHERE lp_name = 'TSM'), 'SCHEDULED', 'REGULAR_SEASON', NULL);
INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 1), 'R2', '2011-06-19', '20:00:00', 'BO3', (SELECT team_id FROM lp_team WHERE lp_name = 'Epik Gamer'), (SELECT team_id FROM lp_team WHERE lp_name = 'Fnatic'), 'SCHEDULED', 'REGULAR_SEASON', NULL);
INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 1), 'R3', '2011-06-20', '13:30:00', 'BO3', (SELECT team_id FROM lp_team WHERE lp_name = 'against All authority'), (SELECT team_id FROM lp_team WHERE lp_name = 'Fnatic'), 'SCHEDULED', 'REGULAR_SEASON', NULL);
INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 1), 'R2', '2011-06-20', '16:00:00', 'BO3', (SELECT team_id FROM lp_team WHERE lp_name = 'TSM'), (SELECT team_id FROM lp_team WHERE lp_name = 'Epik Gamer'), 'SCHEDULED', 'REGULAR_SEASON', NULL);
INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 1), 'R3', '2011-06-20', '19:30:00', 'BO3', (SELECT team_id FROM lp_team WHERE lp_name = 'against All authority'), (SELECT team_id FROM lp_team WHERE lp_name = 'TSM'), 'SCHEDULED', 'REGULAR_SEASON', NULL);
INSERT INTO competition_stage (competition_id, position, name, format, best_of, team_count, group_count) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), 2, 'Phase finale', 'OTHER', 'BO3', 2, 1);
WITH ins AS (INSERT INTO match (competition_id, competition_group_id, stage_id, round_label, date, time, best_of, team1_id, team2_id, status, phase, bracket_side) VALUES ((SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship'), NULL, (SELECT id FROM competition_stage WHERE competition_id = (SELECT id FROM competition WHERE source_key = 'leaguepedia:Season 1 World Championship') AND position = 2), 'Finale', '2011-06-20', '23:00:00', 'BO3', (SELECT team_id FROM lp_team WHERE lp_name = 'Fnatic'), (SELECT team_id FROM lp_team WHERE lp_name = 'against All authority'), 'SCHEDULED', 'PLAYOFFS', 'GRAND_FINAL') RETURNING id) INSERT INTO lp_match SELECT 'leaguepedia:Season 1 World Championship#2#0', id FROM ins;

DROP FUNCTION pg_temp.lp_team(TEXT, TEXT, TEXT, BOOLEAN);
DROP TABLE lp_match;
DROP TABLE lp_team;
